---
- name: Update git repo
  git:
    repo: "{{git_repo}}"
    dest: /home/{{deploy_user}}/{{app_name}}
    clone: no
    accept_hostkey: yes
    key_file: /home/{{deploy_user}}/.ssh/id_rsa
  when: git_repo is defined
  tags: [deploy]
