- hosts: webservers
  roles:
      - { role: node_pkgs_yarn, become: yes, become_user: "{{deploy_user}}" }
      - { role: bower_pkgs_yarn, become: yes, become_user: "{{deploy_user}}" }
      - { role: pip_pkgs, become: yes, become_user: "{{deploy_user}}" }
