---

- name: Install python packages
  apt: name={{item}} state=present
  with_items: [ python-dev, python-pip, python-virtualenv, virtualenvwrapper,
                libffi-dev]

- name: Setup virtualenv
  blockinfile:
    dest: /home/{{deploy_user}}/.bashrc
    block: |
      export WORKON_HOME=~/Env
      source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
    marker: "# {mark} ANSIBLE_MANAGED_BLOCK"
    state: present
  tags: ['install', 'virtualenv-setup']

- stat:
    path: /home/{{deploy_user}}/Env/{{app_name}}
  register: virtualenv_dir
  tags: ['setup', 'virtualenv_setup']

- debug:
    msg: "VirtualEnv exists {{virtualenv_dir.stat}}"
  when: virtualenv_dir.stat is defined

- name: Create virtualenv
  become: yes
  become_user: "{{deploy_user}}"
  shell: "source ~/.bashrc && mkvirtualenv {{ app_name }}"
  args:
    executable: /bin/bash
  when: virtualenv_dir|failed
  tags: ['install', 'virtualenv-setup']
