---
# tasks file for nodejs

- name: Add nodejs apt-key
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Add nodejs repository
  apt_repository:
    repo: deb https://deb.nodesource.com/{{noderepo}} {{ansible_distribution_release}} main
    state: present

- name: Install nodejs
  apt: name={{item}}
  with_items: [ nodejs ]
