---
- name: Ensure .ssh directory exists.
  file:
    dest: /home/{{deploy_user}}/.ssh
    mode: 0700
    owner: "{{deploy_user}}"
    state: directory

- name: Copy ssh private key
  copy:
    src: /home/{{local_user}}/.ssh/id_rsa
    dest: /home/{{deploy_user}}/.ssh/
    mode: 0600
    owner: "{{deploy_user}}"

- name: Copy ssh public key
  copy:
    src: /home/{{local_user}}/.ssh/id_rsa.pub
    dest: /home/{{deploy_user}}/.ssh/
    mode: 0600
    owner: "{{deploy_user}}"
