---
app_name: app

wsgi_enabled: yes
wsgi_user: "{{deploy_user}}"
wsgi_group: "{{deploy_group}}"
wsgi_etc_dir: /etc/uwsgi
wsgi_log_dir: /var/log/uwsgi/
wsgi_run_dir: /run/uwsgi/
wsgi_service_name: uwsgi.service

nginx_dir: /etc/nginx   # Nginx config directory

wsgi_log_rotate: yes
wsgi_log_rotate_options:
- "create 644 {{wsgi_user}} {{wsgi_group}}"
- compress
- copytruncate
- daily
- dateext
- rotate 7
- size 10M

# UWSGI default options (can be redefined for each wsgi app)
wsgi_uwsgi_enable_threads: no
wsgi_uwsgi_reload: no
wsgi_uwsgi_read_timeout: 300
wsgi_uwsgi_processes: 4
wsgi_uwsgi_max_requests: 2000
wsgi_uwsgi_no_orphans: yes
wsgi_uwsgi_max_upload_size: 15M
wsgi_uwsgi_options: []

# Nginx default options (can be redefined for each wsgi app)
wsgi_nginx_port: 80                               # Default port to listen
wsgi_nginx_redirect_www: yes                       # Redirect www.servername to
                                                  # servername
wsgi_nginx_options: []
wsgi_nginx_servernames: "{{inventory_hostname}}"  # Listen servernames
                                                  # (separated by space)

wsgi_nginx_ssl: yes                               # Set yes to enable SSL
wsgi_nginx_ssl_crt:                               # Path to certificate bundle
wsgi_nginx_ssl_key:                               # Path to certificate key
wsgi_nginx_ssl_port: 443
wsgi_nginx_ssl_redirect: no                       # Redirect to SSL port

# Setup your wsgi application here
wsgi_applications:
- name: "{{app_name}}"
